# Untitled

## **프롤로그\(서문\)**

**BIOPset 문서화**

**바이너리 옵션 정 프로토콜\(Binary Options Settlement Protocol, BIOPset\)은 투명한 바이너리 옵션 거래를 위하여 감사 완료된 주문형 검열 방지 피어-투-풀 프로토콜이다.**

**이 플랫폼은 기본적으로 유동성 제공자\("옵션 발행자-매도자"\)에게는 수동적인\(passive\) 수익을 제공하고 공격적인 거래자\("옵션 매수자"\)들에게는 권한을 부여해서 자산 가격의 방향을 예측하여 이익을 얻을 수 있도록 한다.**

**이 프로토콜은 정산\(Settlement\)DAO라고 불리는 분산형 자율 조직의 관리하에 있다.**

## **문서 수정**

**최신 버전\(BIOpset 버전 4\)은 거래자들이 체인링크 토큰\(또는 LINK\)의 가격이 오르거나 내려가는 것을 추측할 수 있게 해줍니다.**

**이것들은 2021년 4월 21일 현재 공식 문서들입니다.**

**이 문서를 검토한 후 질문이나 이견이 있는 경우, Discord 상의 토론에 참여해 주십시오.**

**Discord 상에서 BIOPset 커뮤니티를 확인해보시고 285명의 멤버 들과 어울려서 무료 음성과 문자 채팅을 즐겨보세요.**

[**discord.com**](https://discord.com/invite/4SRYBNdE3r)

**Discord 커뮤니티에 요청하여 BIOPset 최신 정보 확보한 후...**

**만약 불분명하거나 최신 정보가 아닌 것이 있을 경우, pull request\(철회요청\)을 하세요.**

## `문서화 가이드`

**바이너리 옵션 산 프로토콜\(BIOPset\)에 오신 것을 환영합니다. 이 안내서는 옵션 거래 및 하이-로우\(최고-최저점\) 바이너리 옵션의 특성에 아주 처음인 플랫폼 사용자 들을 위해서 준비되었습니다.**

## **구성**

**바이너리 옵션 및 분산 옵션 거래를 처음 접하는 사람 들에게는 BIOPset이 처음에 언뜻 보기에는 엄청나 보일 수도 있을 수 있습니다.  본 공식 문서\(설명서\)는 프로토콜을 이해하기 쉽게 도움을 줄 것이며, 또한  어떠한 혜택을 얻을 수 있는지를 잘 설명해 줄 것입니다.**

**BIOPset 안내 문서화는 세가지 그룹으로 나뉘어 집니다.**

1. **이론**
2. **실전 연습**
3. **참고 사례**

**“이론” 섹션에서는 바이너리 옵션, 분산 거래 및 디자인 철학\(배경\)에 대한 설명을 해 줄 것입니다.  경험이 많은 거래자 들은 이 부분을 건너 뛰고 싶어 할 지도 모릅니다만, 이는 수익률의 생성 방법을 알고자 하는 유동성 제공자 들에게는 읽어 볼 필요가 있다고 생각됩니다.**

[**Theory**](https://docs.biopset.com/theory)

[**/theory**](https://docs.biopset.com/theory)

**“실전 연습” 항목은 단계별 사용자 가이드입니다. 플랫폼에 대한 변경은 업데이트 되지만, 최신 정보를 얻기 위해서는 BIOPset Discord 커뮤니티에 가입/활동하기를 강력하게 권고합니다.** 

[**Practice**](https://docs.biopset.com/practice)

[**/practice**](https://docs.biopset.com/practice)

**“참고사례” 섹션에는 BIOPset과 그 스마트 계약에 관한 모든 관련 사항 들을 포함하고 있습니다.  이 항목은 플랫폼의 최상위에 구축하거나 프로그램 방식으로 인터페이스를 하고자 하는 사용자 들에게는 필수적입니다.**

[**References**](https://docs.biopset.com/references)  


## **정산 DAO**

**정산 DAO 소개**

**바이너리 옵션 정산 프로토콜\(“BIOPset”\)은 정산 DAO가 관리니다.**

**거버넌스 개요**

**정산 DAO는 BIOP 토큰 보유자 들의 유동적 민주주의 방식\(비유적 표현으로 직/간접 민주주의의 혼합형\)을 통하여 관리합니다.  이를테면 “하원”은 Discord 상 커뮤니티 토론에서부터 BIOPset 포럼을 통해 형성된 공식화된 이니셔티브\(결정\)에 투표합니다. 공식화된 결정은 BIOPset 스냅샷 페이지에서 투표에 부쳐집니다.** 

**거버넌스 프로세스\(절차\)**

**정산 DAO의 관리 절차는 다음과 같이 요약할 수 있습니다.**

**토론**

**BIOPset을 개선을 위한 의견 들은 Discord 상에서 논의 됩니다.**

**제안**

**그리고나서 매우 가치있는 의견 들은 BIOPset 포럼에서 공식 제안서로 요약됩니다.**

**투표**

**포럼에서 충분한 토론을 마친 후에, BIOP 관리 토큰 보유자 들은 스냅샷 페이지를 통해서 공식 제안서에 투표합니다.**

**THEORY**

## **BIOPset의 개요**

**BIOPset 의 필수 요소**

## **본 섹션의 항목들 입니다.**

## [**요약**](https://docs.biopset.com/theory/overview/summary)

## [**BIOPset 요약 및 사용자들**](https://docs.biopset.com/theory/overview/summary)

## [**이익**](https://docs.biopset.com/theory/overview/benefits)

## [**BIOPset과 상호작용시 이익**](https://docs.biopset.com/theory/overview/benefits)

## [**Risks**](https://docs.biopset.com/theory/overview/risks) **리스**

## [**BIOPset과 상호작용 시 리스크**](https://docs.biopset.com/theory/overview/risks)

## **요약**

## **BIOPset의 요약 및 그 사용자들.** 

_BIOPset은 세계 최초의 주문형, 피어-투-풀\(peer-to-pool\), 분산 형 바이너리 옵션 거래 프로토콜입니다. 검열 저항으로부 보호 기 위해 이더 리움 네트워크를 기반으로 구축되었으며 정\(Settlement\) DAO의 BIOP 토큰에 의해 통제/관리됩니다. Shalaquiana는 BIOPset 프로토콜 최초 버전의 배후에 있는 익명의 설립자입니다._  


## **스테이크홀더\(보관자\)들**

**BIOPset은 다음과 같은 부류의 스테이크홀더들을 충족시킵니다.**

1. **트레이더\(거래자\)들**
2. **발행자\(매도자\)들**
3. **정자들**
4. **거버너\(의사결정자\)들**

**첫번째의 두 보관자 들은 서로 분산형 바이너리 옵션의 상대방 들입니다. 두 번째의 두 보관자 들은 프로토콜을 만들고 실행을 미세 조정합니다.** 

\*\*이 두 상대방 들은 옵션 계약의 반대 편에 서게 됩니다. 즉, 거래상대방이 기꺼이 팔지 않는다면 파생상품\(바이너리 옵션과 같은\)을 살 수 없습니다.

**모든 참가자는 프로토콜과의 상호 작용에 댜해 재정적으로 무언가를 얻을 수 있는 위치에 있게 됩니다.**  


### **트레이더**

**바이너리 옵션의 구매자들을 BIOPset 명명법에 의해 옵션 트레이더\(또는 트레이더\)라고 부릅니다. 이러한 바이너리 옵션 구매자\(또는 "옵션 보유자"\)는 가격 이동 방향을 감지해서 적극적으로 과감한 투자\(투기\)를 하고 있습니다. 트레이더는 BIOPset 플랫폼의 주요 사용자들 입니다.**  


 \*\*트레이더\(또는 옵션 구매자\)는 BIOPset 거래 프로토콜의 활발한 참여자들 입니다.

### **발행자\(매자\)**

**바이너리 옵션의 매도자들을 BIOPset 명명법에서 발행라고 부릅니다. 이러한 바이너리 옵션 판매자\(또는 "옵션 발행"\)는 바이너리 옵션 구매자의 상대자들 입니다.**

**BIOPset에서 발행자들은 함께 그들의 자금을 모아서 거래자들에게 수동적인 거래상대방 역할을 합니다. 그들은 또한 유동성 공급자\(또는 마켓메이커\)라고도 불립니다.**  


\*\*발행자\(또는 유동성 제공자\)들은 BIOPset에서 수동적인 사용자들입니다.  


**BIOPset의 인프라는 우선적으로 바이너리 옵션 구매자들에게 서비스를 제공하지만, 서비스가 작동하는데 필요한 유동성을 제공하는 것은 옵션 판매자들의 수동적인 풀입니다. 그들은 가게를 차리고 시장에 생명을 불어 넣는\(활성화하는\) 상인들과 같습니다.**

### **정산자**

**장산자들은 트레이더 혹은 작가의 이익 실현을 용이하게 해 주는 인간\(혹은 봇-특정 프로그램\)들 입니다.**

**이들은 옵션 트레이더를 대신하여 “\*내가격옵션\(ITM:in-the-money option\)”을 정함으로써 개입합니다. 또한 이들은 옵션 발행를 대신하여 가치가 없어진 바이너리 옵션을 장함으로써 개입합니다.**

**\*ITM\(in-the-money\)옵션:행사가격이 시장가격보다 낮은 경우 유리하게 행사할 수 있음.**

### \*\*\*\*

### **거버너\(의사결정자\)**

###  ****

**BIOP 토큰을 보유한 자는 누구나 자동으로 거버너\(관리/통제자\)입니다. 관리자들은 유동성 제공자들에게 합리적인 수익률을 보장하기 위해 BIOPset 한도를 미세 조정할 책임이 있습니다.**

**유동성 제공자들은 거버너일 필요가 없으며 그 반대의 경우도 같습니다.**

**이상적으로는 거버너들도 유동성 제공자이며 이는 장/단기 인센티브 구조를 조정합니다.**

## \*\*\*\*

## **이익**

**BIOPset과 상호작용시 이익**

**BIOPset은 트레이더\(또는 투기자\)를 위한 무신뢰 환경\(믿을 수 있는 중개자가 필요 없는\)의  바이너리 옵션 거래 솔루션을 제공합니다. 이 플랫폼은 즉각적인 액세스를 제공하고 투기자금은 보유하지 않는 최초의 바이너리 옵션 플랫폼입니다. 거래자 옵션이 가치가 있는\(또는 ITM-내가격옵션 상황\) 즉시, 그들은\(정자로서\) 자신들의 권리를 행사할 수 있고 제3자에게 의존할 필요 없이 그들의 지갑으로 직접 ETH를 받을 수 있습니다.**

**트레이더의 가치가 없어진 옵션은 발행\(또는 유동성 제공자\) 상대방의 이익에 대한 유동성 풀\(일명 "하우스"\)에 축적합니다.**

\*\*BIOP 토큰을 가진 옵션 발행는 투자자이자 소유주가 되어 하우스 역할을 합니다. 이는 중앙 집중식 바이너리 옵션 거래 플랫폼에서는 거의 볼 수 없는 이점을 제공합니다.

**BIOPset 플랫폼과의 모든 상호작용은 활용 보상 기간 동안 BIOP 토큰을 획득합니다. BIOP 보상은 그들의 투표권을 위해 판매되거나 스테이킹\(토큰-&gt;지분\) 될 수 있습니다.**

[**Rewards                                                                                        /references/tokens/rewards**](https://docs.biopset.com/references/tokens/rewards)  
  
**나에게 또 다른 혜택은 무엇일까?**

**BIOP 보상을 받는 것 외에, 모든 참가자들은 그들의 BIOPset 참가에 대하여 재정적 이득을 취할 수 있는 위치에 있게 됩니다. BIOPset은 다음 4 부류의 스테이크홀더\(보관자\)들이 적절한 보상을 받을 수 있도록 보장합니다.**

1. **트레이더**
2. **발행자\(매자\)**
3. **정자**
4. **거버너\(의사결정자\)**

**거버너\(의사결정자\)들은 항상 각각의 스테이크홀더들이 그들의 활동에 대해서 어떻게 보상을 받는지를 정확하게 결정하기 위한 권리를 계속 보존합니다.**

### **트레이더**

**트레이더\(또는 옵션거래자\)들은 활발하게 바이너리 옵션을 구매하며 가격 방향을 정확하게 예측 할 경우 그들의 재산을 2배로 만들 수 있는 잠재력을 갖고 있습니다.** 

**이들은 또한 정자들이 될 수 있습니다.\(아래를 참조\)**

### **발행자\(매자\)**

**발행자\(또는 옵션 발자\)들은 풀 내에서 다른 판매자들과 함께 바이너리 옵션을 소극적으로 판매합니다. 이들은 BIOPset의 마켓메이커\(또는 유동성 공급자\)이기도 합니다. 유동성 공급자 들은 시장 조성\(옵션 작성\)에 대한 매우 경쟁력 있는 수익률을 얻게 됩니다.** 

**발행도 정산들이 될 수 있습니다.\(아래를 참조\)**

## **정자**

**정자들은 서비스 제공에 대한 리스크 없는 수수료를 받습니다. 기본 액수는 옵션 가치의 0.2%이며, 결과적으로 100만불 정도를 행사하거나 만기시에 잠재적으로 2천불을 벌 수 있게 됩니다.**

\*\*정산자들은 옵션 거래자를 대신해서 인더머니\(ITM\) 옵션을 산하며, 이들은 유동성 제공자를 대신하여 아웃오브머니\(OTM\) 옵션을 정하며 개입합니다.

**누구든지\(사람, 봇, 혹은 AI\) 전자지갑과 충분한 가스\(gas\)만 있으면 정자가 될 수 있습니다.**

### **거버너\(의사결정자\)**

**거래 수수료는 현재 20 기본 포인트\(0.2%\)로 설정되어 있으며, 그 수익금은 정DAO의 금고에 적립을 진행하게 됩니다. 거버너들은 정DAO 금고의 자금을 관리하며, 그들은 또한 \(투표 위임을 통해\) BIOP토큰을 지분으로 보유하고자 하는 토큰 보유자에게 직접 그 수수료의 일부를 분배하도록 선택할 수도 있습니다.**

**거버너들은 금고를 관리하고 유동성 제공자들에게 합리적인 수익률을 보장하기 위해 BIOPset의 매개 변수를 미세 조정할 책임이 있습니다. 이들은 장기적으로 플랫폼 사용자 수를 증가시키기위한 인센티브제도를 채택할 수 있습니다.**

**트레이더, 발행 및 정자들은 모두 BIOP 토큰을 보유함으로서 의사결정 계획에 참여할 수 있으며, 이들의 신뢰를 얻은 거버너에게 투표권을 위임할 수도 있습니다.** 

**투표권은 사람의 주소로 위임하는 대신 원하는 변경을 할 수 있도록 사전에 감사 완료되어 만들어진 스마트 계약서에만 위임할 것을 강력히 추천합니다.**

##  ****

## **위험요소**

##  **BIOPset과 상호작용시 위험요소**

**바이너리 옵션 거래에는 위험요소가 있지만 모든 바이너리 옵션이 동일한 위험요소를 동반 하지는 않습니다. 당신이 만약 유동성 공급자\(또는 발행\)라면 바이너리옵션 보유자\(또는 트레이더\)와 바이너리 옵션 정산자\(정자\)와는 다른 위험에 직면하게 됩니다.**

## **스테이크홀더\(보관자\) 리스크**

**BIOPset 사용을 시도하기에 앞서 거래 옵션의 기본 사항들을 확실하게 숙지하기 바랍니다. 또한 4 부류의 스테이크홀더\(보관자\)들의 프로토콜의 독특한 리스크 들을 이해하는 것도 중요합니다.**

### **트레이더**

**BIOPset에서 바이너리 옵션을 구매하는 것은 프로토콜과의 상호작용 중 가장 위험한 형태입니다. 트레이더들은 바이너리 옵션 취득을 위하여 프리미엄을 지불해야 하며, 콜 바이너리 옵션 혹은 풋 바이너리 옵션의 보유 여를 선택해야합니다.** 

**콜\(콜 바이너리 옵션\)은 거래자가 자산 가격이 향후 오를 것이라고 믿고 포괄적으로 낙관적 전망/전략을 수립합니다. 하지만 자산 가격이 내릴 경우 트레이더들은 전체 프리미엄을 모두 잃게 됩니다.**

**풋\(풋 바이너리 옵션\)은 거래자가 향후 자산 가격이 내릴 것이라고 믿고 포괄적으로 약세 전망/전략을 수립합니다. 하지만 자산 가격이 오를 경우 트레이더들은 전체 프리미엄을 모두 잃게 됩니다.**

[**Buying Options                                                                  /theory/fundamentals/buying-options**](https://docs.biopset.com/theory/fundamentals/buying-options)

### **발행자\(매자\)**

**BIOPset에서 바이너리 옵션의 판매도 리스크가 없는 프로토콜 활용은 아니며, 변동 혹은 고정 이자율을 제공하는 분산화된 렌딩 프로토콜의 활용과는 다릅니다. 바이너리 옵션 판매자는 리스크를 안고 투입한 자본을 잃을 수도 있습니다. 발자 들은 거래자 들의 상대방이며 만일 거래자 들이 지속적으로 성공적인 결과를 얻는다면 그들의 모든 투자금을 잃을 수도 있습니다.**

[**Selling Options                                                                   /theory/fundamentals/selling-options**](https://docs.biopset.com/theory/fundamentals/selling-options)

### **정자**

**BIOPset 상에서의 바이너리 옵션 정산은 리스크 없는 상호작용입니다.**

[**Settling Options                                                             /theory/fundamentals/exercising-options**](https://docs.biopset.com/theory/fundamentals/exercising-options)

### **거버닝\(의사결정 행위\)**

**의사결정 행위는 BIOP 토큰 보유를 포함하며 리스크가 없지 않습니다. BIOP의 가격이 수요/공급에 따라서 오르고 내리기 때문입니다.**

[**BIOPset Governance                                                                             /theory/governance**](https://docs.biopset.com/theory/governance)

\*\*요약해서 정리하자면, 조사결과가 자산가격 상승\(오라클 업데이트 받기 전에\)을 가리키면 콜 옵션을 구매하고, 그렇지 않을 경우 풋 옵션을 구매 하십시오. 조사 결과 옵션이 거의 동일하다고 하면 발행자\(매자\)가 되십시오. 제로 리스크를 원치 않는다면 정산 션입니다. 만약 프로토콜을 선호하시고, 잠재적인 BIOP 가격 변동이 상관 없으며, 정DAO 관리/통제를 돕기를 원하시면 BIOP을 구매하십시요.  

## **BIOPset의 기초\(기본원칙\)** 

**본 섹션의 항목 들**

[**구매옵션**](https://docs.biopset.com/theory/fundamentals/buying-options)

**바이너리 옵션 구매에 대한 설명과 프로토콜 수준에서 수행되는 작업** 

[**판매옵션**](https://docs.biopset.com/theory/fundamentals/selling-options)

**바이너리 옵션 판매에 대한 설명과 프로토콜 수준에서 수행되는 작업** 

[**정산옵션**](https://docs.biopset.com/theory/fundamentals/exercising-options)

 **바이너리 옵션 정에 대한 설명과 프로토콜 수준에서 수행되는 작업**

## \*\*\*\*

## **구매 옵션**

## \*\*\*\*

**바이너리 옵션 구매에 대한 설명과 프로토콜 단계에서 수행되는 작업.** 

**바이너리 옵션은 일부 다른 자산 혹은 자산의 크기로부터 그 가치를 도출하는 투기적 성격의 금융상품\(또는 금융수단\)입니다. 결국, 모든 바이너리 옵션은 완전히 가치가 없어지거나 혹은 미래에 특정 양의 계산 가능한 가치있는 액수가 됩니다.**

**구매 옵션에 대한 이 섹션은 미디엄\(Medium\)에 게재된 자세한 설명에서 발췌한 것입니다. 이론을 건너뛰고 바로 거래로 들어가려면 사용 설명서를 살펴 보십시오.**

### **가격 예측\(투기적 측면에서\)**

**BIOPset은 가격 예측을 용이하게 해 줍니다. 바이너리 옵션 구매의 전적인 목적은 가격 변화에 대한 방향을 잡는 것입니다.**  

**바이너리 옵션은 본질적으로 all-or-nothing\(전부 혹은 제로\)의 금융 파생상품입니다. 트레이더 들은 돈을 벌거나 잃는 것 - 둘 중 하나이며, 그 중간\(혹은 또 다른 가능한 결과물-소득\)은 없습니다.**

**파생상품으로 불려지는 것은 그 가치가 일정 기간이 지난 후에 다른 어떤 것으로부터 파생 되기 때문입니다. 그 일정 기간 후에 옵션 들은 기간만료 되었다고 합니다.  바이너리 옵션이 가치를 발생시킨 그 다른 무엇을 기초\(또는 기초 자산\)이라고 부릅니다.**

**BIOPset 버전4에서 활용된 정보 입력 들은 체인링크\(Chainlink\)로부터 제공됩니다. 하지만, 기초자산은 금융자산이나 암호화화폐일 필요가 없으며 비오는 날과 같은 날씨의 상, 또는 미래에 변화를 가져올 속성을 가진 다른 어떤 것일 수도 있습니다.**

**바이너리 옵션은 투기성 상품입니다. 이 상품을 구매하는 사람들\(옵션 구매자/보유자\)들은 통상 어떠한 현상의 미래 상태에 대한 강한 의견을 갖고 있습니다. BIOPset 버전4에서 바이너리 옵션을 구매하는 트레이더 들은 그들이 선택한 가격거래묶음\(예를들어 비트코인/미달러의 페어와 같은\)의 미래 가격에 대하여 전형적으로 진지한 의견을 갖고 있습니다.**

**보다 정확하게는 트레이더 들은 기초자산 가격의 변동 방향을 예측함에 있어서 적극적으로 개입되어 있습니다. 이들은 돈을 절약하고 싶어서 소극적으로 옵션을 구매하지는 않습니다.  “경고:저축한 돈을 절대 사용하지 마십시요!”**

**트레이더 들은 그들이 미래에 대해 아는 것\(그들 생각으로\)에 근거하여 돈을 벌기 위한 플랫폼을 활용합니다.** 

옵션 구매자

옵션 구매자들은 BTC/USD의 가격 이동 방향에 대한 의견을 가집니다. 오직 두 방향\(상승 혹은 하락\)만이 있으며, 그 중 하나를 선택합니다.

한가지 예를 들어보면, 앨리스는 BTC/USD 페어의 가격이 오를 것이라고 믿으며 그렇게 되리라고 매우 강하게 느끼고 있습니다. 그래서 앨리스는 그 의견에 기꺼이 10 ETH를 걸 것을 약속하고 BIOPset 상에서 옵션 판매자 풀에 대해 “업\(상승\)” 포지션을 선택합니다.

옵션 판매자

옵션 판매자들은 BTC/USD의 미래 가격에 대해서 반대 시점을 갖고 있어야만 합니다. 의미상, 옵션 판매자는 상대편이며 반대 입장을 취합니다.                                                                                                         BIOPset에서 어떤 개인도 독자적으로는  반대 입장을 가질 수 없으며, 풀\(또는 하우스\)에 약속한 기금에 준하여 판매자 그룹으로 반대 입장을 갖게 됩니다. 

앨리스의 강력한 의견을 고려하여 풀은 어쩔 수 없이 반대 입장을 갖고 가격 “하락”에 10 BTC를 투입합니다. ****

### **콜옵션과 풋옵션**

**BTC가격의 상승으로 돈을 벌기를 원하는 트레이더 들은 콜옵션을 구매하고, 가격 하락을 예측한다면 풋옵션을 구매합니다.** 

**가격의 향방 만이 관건입니다.** 

**가격 상승/하락의 폭은 중요하지 않습니다. BIOPset 상에서는 BTC 가격이 1달러가 상승하든, 1,000달러가 상승하든 콜옵션 보유자가 승리하며, 반대로 BTC 가격이 1달러 또는 1,000달러가 하락하면 풋옵션 보유자가 이기게 됩니다.\(승리/이긴다는 의미는 돈을 딴다는 의미라고 할 수 있음\)**

### **행사 가격**

**바이너리 옵션의 구매가 이루어지는 순간의 BTC 가격을 행사 가격\(strike/exercise price\)이라고 부르며, 항상 BIOPset UI\(사용자 인터페이스\)에 나타납니다.**

**정확히 말하자면, Chainlink Oracle에 따라서 옵션이 구매되는 순간의 BTC 가격입니다.**

**이러한 행사 가격에 따라서 옵션의 가치가 변화하기 때문에 유의하는 것이 중요합니다.**

**풋옵션 보유자 들은 오라클로부터 첫번째 업데이트를 받을 때, 행사가격이 BTC 가격을 초과한다면 그들의 옵션을 정할 수 있습니다. 반대로 콜옵션 보유자 들은 오라클로부터 첫 업데이트를 받았을 때 BTC 가격이 행사 가격을 초과한다면 옵션을 정산 수 있습니다.**

### **기한만료**

**기한 만료 시, 기존의 바이너리 옵션의 가치는 없으며\(또는 내재가치 제로 보유\), 이들이 가졌던 내재 가치는 기한 만되었습니다. 이러한 관점에서 이 옵션을 행사할 권리가 더이상 존재하지 않습니다.** 

**BIOPset에는 기한만료라는 개념은 없습니다. 만료기간이 무한대로 설정되어 있으며, 이는 옵션의 가치가 오라클 업데이트를 받으면서 정해지기 때문입니다.** 

### **정산**

**사람 또는 프로그램도 옵션을 정하고 오라클 업데이트를 받은 후에 0.2%의 정산 수수료를 받습니다.** 

**결과적으로 콜 또는 풋 옵션 보유자 들은 옵션을 스스로 정하고 그 0.2% 수수료를 받을 수 있는데, 이러한 경우에 옵션 지급액은 99%입니다.\(BIOPset이 1%의 거래수수료를 부과합니다.\)**

**그렇지 않으면 임의의 플랫폼 참여자가 금융지분이 있는 경우에 그 옵션을 정하고 0.2% 수수료를 가져갈 수 있습니다. 이러한 경우 옵션 지급액은 98.8%\(옵션을 정하는 사람/봇\(프로그램\)에게 0.2% 지급됨\)로 감소하게 됩니다.**

**정 역할 트랜잭션은 항상 위험이 없습니다. 이 조치를 취하기 전에 정확한 보상을 확인할 수 있기 때문입니다.**

## **판매옵션**

**바이너리 옵션 판매에대한 설명과 프로토콜 수준에서 수행되는 작업.** 

**BIOPset에서는 옵션 판매자들은 마켓 메이커\(혹은 유동성 공급자들\)입니다. 판매자\(공식적으로는 발행라고 부름\)들은 가격 정책에 의견 제시를 원하는 옵션 구매자\(트레이더\)들의 반대 입장을 취하기 위해서 함께 그들의 자금을 공동 출자합니다.**  

**BIOPset 플랫폼에서 발행들은 항상 활발한 트레이더들의 소극적인 상대방입니다.**  

\*\*상대방들은 바이너리 옵션 계약의 반대편에 서게 되는데, 상대방이 없이는 바이너리 옵션의 구매는 불가능합니다.

**발행가 공동 출자 풀에 기여할 때 마다, 그들은 그 기금내의 그들의 지분 비율에 따라서 pETH\(또는 poolETH\)를 발급 받습니다. 이러한 이유에서 풀에 제공하는 기금을 가끔 스테이킹이라고도 합니다.**  

### **이더리움 스테이킹** 

**BIOPset 버전4는 트레이더들에게 Chainlink\(또는 LINK\) 가격 방향의 투기적 예측 능력을 제공합니다. ETH로 출자한 기금풀이 이를 가능하게 합니다. 옵션 판매자 들은 이 공동 출자 풀에 그들의 개인 분담금을 직접 예치하고 대신 pETH를 받습니다.**

\*\*발행가 받는 pETH의 액수는 기금\(pool\) 내 ETH 전체 수량에 대한 상대적인 기여도를 나타냅니다.

\*\*pETH는 위험한 자산입니다. ETH의 가치는 시간이 지나면서 기금\(pool\)의 성과에 따라서 변화합니다. 발행 기금 풀의 성과가 좋을 경우 그 가치는 엄청나게 상승할 수도 있지만, 만약 트레이더들이 좋은 성과를 낸다면 pETH의 가치 없어 질 수도 있습니다.   

**pETH는 ETH와 일대일로 발급되지만, 그 상환\(현금화\)은 적지 않습니다.**

### **상환 가치**

**pETH는 ETH로 교환할 수 있습니다. 하지만 그 상환 가치는 바이너리 옵션이 무가치 만료\(혹은 OTM이라고도 함\), 가치 보존\(혹은 ITM\) 그리고 옵션 행사 때 마다 변합니다.**

Shalaquiana는 아래와 같은 시나리오\(가설\)로 이와같은 상황을 가장 잘 표현합니다:

이를테면 BIOPset이 방금 시작되었고 Brock\(일명 황소\)은 재량껏 처리할 수 있는 1 ETH를 갖고 있다고 가정해 봅시다. 그는 오로지 재미를 위해서 바이너리 옵션을 팔기로 결정합니다. 그에게는 맘대로 처분할 수 있는 재산이고, 그에는 충분한 재산 있습니다.

Brock은 첫번째 작성자로 신규 ETH 풀에 1 ETH를 기여한 댓가로 1 pETH를 받아서 보관하는데 Brock의 1 pETH는 ETH 풀의 100%에 해당 됩니다.

또한 Tahila\(일명 암호랑이\)가 동참해서 2 ETH를 기여했다고 가정한다면, 그녀는 2 pETH를 받습니다. 여기서 Brock의 1 pETH는 ETH 풀의 33%이며, Tahila의 2 pETH는 풀의 나머지 66%에 해당 됩니다.

마지막으로 Jose\(일명 잭래빗\)가 LINK 가격이 상승할 것 이라는 의견을 갖고 BIOPset에서 2 ETH 가치에 해당하는 LINK 가격으로 바이너리 풋옵션을 구매합니다.  이후 오라클 업데이트를 받고 옵션은 무가치의 OTM으로 완료되고, Jose는 잘못된 예측으로 2 ETH를 잃습니다. 

Jose의 손실 풀의 이익이 됩니다. Jose의 바이너리 옵션 종료 시점에 풀에는 총 5 ETH가 있게 됩니다. 만약 Brock이 풀에서 그의 지분을 인출하고자 한다면 그의 33% 지분은 1.66 ETH이며, 5 ETH의 33%를 수령하게 됩니다.

**Shalaquiana의 설명은 명확하게 이해되지만, 지나치게 단순화시킨 이야기입니다.** 

**BIOPset에서 가장 중요한 부분인 시장의 형성, 즉 유동성 동결이 남아 있습니다.**  

### **유동성 잠금\(동결\)**

**BIOPset에는 두 종류의 유동성 잠금 제도가 있습니다.**

1. **담보 잠금**
2. **예치금 잠금**

**트레이더들은 담보 잠금을 작동시키며, 발행들은 그들이 유동성에 기여할\(높힐\) 때 마다 예치금 잠금을 실행합니다.**

### **담보 잠금**

**담보 잠금은 옵션이 구매될 때 마다 생기며, 풀 기금의 잠금은 옵션 만기 혹은 옵션이 ITM으로 행사될 때 까지 남아 있게 됩니다. 담보 잠금은 풀 기금과 거래자 기금 모두를 포함합니다.**

**이 기간\(락업-거래정지 기간이라고 함\) 동안에는 발행들은 ETH 풀에 있는 그들 각각의 잠겨있지 않은 유동성 지분을 인출만 할 수도 있습니다.**

**다시한번, Shalaquina가 최고의 설명을 합니다.**

**인출권한은 오로지 유동성 제공자에게만 주어지며, 그들의 잠겨 있지 않은 유동성의 지분에 대해서만 가능합니다.**

예를 들어서, 풀에 6 ETH가 있고 당신의 몫이 50%\(발급된 총 6 pETH 중 당신은 3 pETH를 갖고 있다는 의미\)인데, 갑자기 트레이더 한명이 2 ETH 상당의 바이너리 콜 옵션을 LINK 가격 상승을 확신하며 구매한다고 가정해 본다면, 그 구매는 잠금 없는 유동성을 6 ETH에서 4 ETH로 감소시키는 담보 잠금이라는 결과를 낳게 됩니다.

만약 당신이 담보 잠금 기간에 유동성 인출을 원한다면, 2 ETH\(잠금 해제된 4 ETH 중 50%\)까지만 인출할 수 있습니다. 만일 담보 잠금이 만료되어 해제될 때까지 기다린다면, 당신은 3 ETH\(잠금 해제된 6 ETH의 50%\) 전부를 인출할 수 있습니다. 만일 결제될 때 트레이더들의 바이너리 옵션이 ITM일 경우, 담보 잠금 상태의 자금 들은 모두 트레이더의 몫이 됩니다.

### **예치금 잠금**

**발행들은 최소 기간 동안 ETH를 풀에 예치하며, 이는 두번째 형태의 거래정지 기간입니다. 예치금 동결의 정지 기간은 발행가 새로운 자금을 풀에 투입할 때 마다 리셋되며 줄어 들지는 않습니다.**

**BIOPset 버전3의 거래 정지 기간은 14일간이며 이 기간 중 풀로 부터 인출되는 어떤 자금에 대해서도 조기 인출 수수료\(1%\)가 부과됩니다. 정지 기간 후에는 자금은 수수료 발생 없이 인출 수 있습니다.** 

**\*\***14일간의 정지 기간은 거버넌스\(협의체\) 결정에 의해 변경될 수도 있습니다.

#### **조기 인출 수수료**

**조기 인출 수수료 1%가 있으며, 치금 거래정지 기간 동안에는 발행들 만이 잠금해제된 풀의 유동성에 있는 지분의 권리가 있을뿐 입니다.**

**14일의 정지기간 만료 후에는 조기 인출 수수료가 적용되지 않으며 수수료 요율은 거버넌스\(협의체\) 결정에 따라서 변경될 수도 있습니다.**

## **정 옵션**

**바이너리 옵션 결제에대한 설명과 프로토콜 수준에서 수행되는 작업.**

**이 옵션은 BIOPset 프로토콜이 원활하게 실행하도록 지원함으로써 이익을 취할 수 있는 리스크 없는 수동적 기회입니다.**

**정 옵션은 ITM으로 옵션 행사를 하거나 OTM으로 옵션 만기로 거래를 마감하는 과정입니다. 이 두가지 조치는 버튼 하나를 클릭함으로 완료되며 둘 다 같은 종류의 거래입니다.**

**옵션 결제를 결정하기 위해서 사용자는 “Settle\(정산\)” 페이지에서 현재 오픈 옵션\(열려있는 옵션\)을 볼 수 있습니다. 이 탭에서 버튼을 누르며 오픈 옵션을 보고 정할 수 있습니다. 각 오픈 옵션은 옵션을 완료했을 때 받게되는 수수료를 표시하며 수수료\(기초자산의 경우 디폴트 값은 ETH\)는 사전에 정해 집니다.** 

_**정 수수료는 디폴트로 0.02%**_

### **정산에대한 활용보상**

**활용보상이 활성화되어 있는 동안에는 BIOP 보상도 매 옵션이 정될 때 마다 주어집니다. BIOP액수는 현재 정산 대기 중인 옵션의 수량으로 결정됩니다. 대기중인 옵션이 많을수록 사용자가 받는 BIOP의 액수도 더 많아집니다.** 

##  ****

## **BIOPset 토큰**

**아래는 본 섹션의 항목 들 입니다.**

[**pETH 토큰**](https://docs.biopset.com/theory/tokenomics/pooleth)

**pETH는 유동성 제공 토큰입니다.**

**BIOP 토큰**

**BIOP은 거버넌스 토큰입니다.**  
  


### **PETH 토큰**

**PETH는 유동성 제공 토큰입니다.**

**poolETH\(혹은 pETH\)는 유동성을 제공한 후에 옵션 판매자\(또는 발행\)들에게 주어지는 토큰입니다. 여기서 토큰은 스테이킹 토큰\(지분화한 토큰\)이라고도 합니다.**  

**$PETH는 모든 발행들이 제공하는 자금 풀의 토큰 보유자 지분을 나타냅니다. PETH가 어떤 역할을 하는지 이해하려면 BIOPset Fundamentals의 Selling Options 섹션을 참고하십시오.**  


### **BIOP 토큰**

**BIOP는 거버넌스 토큰입니다.**

**BIOP 토큰은 BIOPset 프로토콜을 통제하는데 사용되며 정확하게 총 3,100만개의 $BIOP토큰이 실제로 있습니다. $BIOP 토큰은 표준 ERC-20 토큰이며 티커 BIOP을 사용합니다.**

**BIOP 토큰의 대다수\(45.2%\)는 플랫폼 활용 보상으로 할당됩니다. 보다 자세한 사용 내역은 아래의 “토큰 분배” 섹션을 보기 바랍니다.**  


### **토큰 스펙**

| **세부사항** | **속성** |
| :--- | :--- |
| **토큰 약자\(Ticker\)** | **BIOP** |
| **토큰 타입** | **ERC-20** |
| **토큰 수요** | **31,000,000** |

### **토큰 분배**

| **Specification 세부사항** | **Percentage 백분율** | **Amount 액수** |
| :--- | :--- | :--- |
| **Utilization Rewards 활용보상** | **45.2%** | **14,000,000** |
| **Bonding Curve 본딩커브** | **19.4%** |   **6,000,000** |
| **Initial Tiered Coins Offering ITCO오퍼링** | **19.4%** |   **6,000,000** |
| **Dex Rewards Dex 보상** |   **5.8%** |   **1,800,000** |
| **Developer Fund 개발자기금** |   **4.3%** |   **1,340,000** |
| **Uniswap Listing 유니스왑 상장** |   **3.2%** |   **1,000,000** |
| **V2/V3 Repayment 버전2/3 상환** |   **1.1%** |      **340,000** |
| **Airdrops 무상지급\(증자\)** |   **1.1%** |      **340,000** |
| **V2/V3 Swap 버전2/3 스왑** |   **1.1%** |      **340,000** |

#### **활용 보상**

**대다수\(45.2%\)의 $BIOP은 거래 채굴 메커니즘을 통해서 커뮤니티 가입자\(멤버\)들에게 분배될 예정입니다. 거래 채굴은 보상 플랫폼 참가자들의 과정입니다. 그래서 이 보상은 거래 채굴 보상이라고도 합니다.**

**이 토큰에서 10%는 토큰 생성 이벤트 시점에서 향후 3년에 걸쳐서 월 2.5% 확정으로 잠금 해제 될 것입니다.**

**거래 채굴 활동은 BIOPset 버전1 메인넷 개시와 함께 시작 되었습니다. 추가정보를 위해서는 Benefits\(이익\) 섹션을 참고 하십시오.**

#### **본딩 커브\(IDO 토큰판매가격 산정방식\)**

**본딩 커브\(곡선\)은 덱스\(탈중앙화거래소\)에서 유동성 부족의경우, DAO에 의해서 사용됩니다. 본딩 커브의 모든 스왑 수수료\(양방향 모두 기본값 제로 설정\)는 BIOPset금고로 들어갑니다. 토큰들은 개시로부터 6개월간 동결되었다가 사용 능력이 생기면 본딩 커브는 DAO로 전환됩니다.**

**보다 상세한 내용은 Reserve Bonding Curve를 보십시오.**  


#### **단계별  초기본딩커브오퍼링\(Tiered IBCO\)**

**BIOPset유동성으로의 개발과 부트스트랩\(무료 S/W 도구모음\)에대한 초기 자금은 단계별 IBCO를 통해서 모아집다.** 

**Tiered IBCO에대한 보다 자세한 사항.**

#### **덱스 보상**

**유니스왑 유동성을 활성화\(인센티브를 통한\)하기 위해서 LP\(유동성제공\)토큰을 스테이킹하는 유니스왑 유동성 제공자 들에게 인센티브를 주게 됩니다.**

#### **개발자금**

**개발자금은 건전한\(안정적인\) 조직이 갖춰 질 때까지 개발, 전개, 보조금 및 DAO공격의 예방 자금 등으로 사용됩니다.**  

**개발자금 중에서 10%는 나머지 90%의 3년 간에 걸친 락업\(동결\) 이후 토큰 생성 이벤트\(TGE\)에서 해제됩니다.**

#### **유니스왑 상장**

**Uniswap에서 시작가를 제공하고 거래를 가능하게 하기 위해서 팀은 ITCO 종료 후, Uniswap 유동성 풀에서 BIOP과 이더리움을 동결시킵니다.**

#### **버전2/3 상환**

**BIOPset의 버전2와 버전3 기간 동안 우월한 자들이 전체 유동성 풀에서 승리했습니다. 이제는 그러한 일이 다시 일어나지 않도록 여러가지 조치가 취해졌습니다. 그러한 이유로 이더리움을 잃은 사람들에게 그들이 손해본 이더리움과 동일한 액수의 BIOP을\(1 BIOP당 0.0001ETH 이상으로\) 보상해 줄 것 입니다.**   


#### **무상지급\(에어드랍Air-Drop\)**

**커뮤니티에 활발한 참가와 성장에 대한 인센티브로 BIOP 상품으로 다양한 무상 지급 이벤트를 계획하고 있습니다.**

#### **버전2/3 스왑**

**이전 BIOP 버전으로 거래 채굴에 참가해서 구 버전의 BIOP 토큰을 가진 사용자들은 새로운 BIOP 버전4를 받게 됩니다.** 

##  ****

## **BIOPset 거버넌스**

**정산 DAO: BIOP 통제하의 DAO\(탈중앙 자율조직\)**

**정산 DAO에 강력한 참여는 플랫폼 디자인\(설계\)와 인센티브 제도의 궁극적인 염원입니다. 그럼으로서 DAO의 지지세력\(고객층\)은 BIOPset 스마트 계약서가 시작된 후에는 눈에 띄게 변화해야 합니다. 따라서, DAO는 두가지 뚜렷한 특성을 갖고 있습니다.**

1. **부트스트랩 단계\(혼자 힘으로 시작\)**
2. **지속적인 구성 단계**

**두단계 모두 다음과 같은 우선 순위를 포함합니다:**

1. **Security 보안**
2. **Transparency 투명성**
3. **Best Practices 모범사례**
4. **Liquid Democracy 유동적 민주주의**

**보안**은 플랫폼에 저장된 자금을 안전하게 보관하는 것에 대한 끊임없는 집착으로 이해되어야만 합니다. 이것을 최우선 순위로 삼는다는 것은 모든 메인넷 스마트 계약 구축을 감사하고 버그바운티\(취약점 제보에대 보상\) 시스템을 확립하는 것을 의미합니다.  


**투명성**은 투명한 프로세스를 구축하고 열린 담화와 공개 토론을 함양하는것을 의미합니다.  


**모범 사례**는 스마트 계약 구축과 효과적인 거버넌스\(타임락, 멀티시그\(공동서명\), 포럼, 무기명/온체인 투표 등\)의 가치와 복원력을 향상시키는 전문화된 표준을 지속적으로 탐색하고 구현하는 것으로 이해되어야 합니다.  


**유동적 민주주의**란 DAO 회원들이 직접 투표하는 특권 혹은 그 특권을 대리인에게 위임할 권리를 소유하는 것을 의미합니다.



[https://en.wikipedia.org/wiki/Liquid\_democracy​](https://en.wikipedia.org/wiki/Liquid_democracy%E2%80%8B%EB%8B%A4%EC%9D%8C)  다음 사이트의 자료를 참고 하십시요.

##                       ****

**부트스트랩 단계는 특별한 한가지 측면에서 지속적인 구성 단계와 다릅니다.**  


**발행의 경험을 전적으로 고려하는 것.**  


**이는 각 DAO 멤버들이 하나 투표권을 소유하는 순수 민주주의를 일시적으로 구축함으로 이루어졌습니다. 이러한 잠정적인 거버넌스\(통제\) 구조는 BIOPset 버전4가 출시될 때까지 지속될 것입니다. 이 기간 동안 DAO의 멤버쉽은 지금까지의 BIOPset 버전2/3의 발행들만의 용맹한 그룹으로 구성될 것입니다. BIOPset 버전 2/3 유동성 풀의 과거 발행자들은 DAO에 제안서를 제출하고 모든 계획에 투표할 수 있는 특권을 갖습니다.**  
  


**PRACTICE**

## **사용매뉴얼**

**본 BIOPset 사용 매뉴얼은 단계별 사용자 안내서입니다.** 

**본 섹션의 항목 들 입니다:**

#### [**단계별 구매 옵션**](https://docs.biopset.com/practice/guides/buying-options-step-by-step)

[**거래를 위한 설명**](https://docs.biopset.com/practice/guides/buying-options-step-by-step)

[**단계별 판매 옵션**](https://docs.biopset.com/practice/guides/selling-options-step-by-step)

[**정산을 위한 설명**](https://docs.biopset.com/practice/guides/selling-options-step-by-step)

[**단계별 정산 옵션**](https://docs.biopset.com/practice/guides/exercising-options-step-by-step)

[**구매자 개입을 위한 설명**](https://docs.biopset.com/practice/guides/exercising-options-step-by-step)

##  ****

## **단계별 구매옵션**

**거래를 위한 설명**

## **단계 1: BIOPset 방문**

**브라우저에서 URL** [**http://biopset.com**](http://biopset.com) **을 입력**

## **단계 2: 지갑 연결**

**“연결” 버튼을 누르면서 지갑에 연결. 제공자\(공급자\) 선택하십시오.**

**사용자 안내서에서 해당 부분은 자주색 원으로 표시됩니다.**

![](https://lh5.googleusercontent.com/qSifQ6UD79-MrP7Mt0sb53S8c4OZejXiej0RTlWsGw8R-_yjjgAwret_FW1YKTvDk_8yg_l9DjUDfmSSsxpuLC3WhIIj9DP6q0I1tAl3Da2rn8Kx8_9rE8L0tVyJLp01PNlKKbBM)

**연결\(Connect\) 버튼 클릭**

## **단계 3: 옵션 사이즈 설정**

**당신이 원하는 리스크 만큼의 ETH 액수를 빨간색 박스에 입력하십시오. 그 액수는 옆에 나타낸 “최대 베팅 사이즈” 액수보다 반드시 적어야 합니다.**

**정확한 방향을 선택해서 이길 수 있는 금액은 “WIN” 아래의 파란색 박스에 나타납니다.**  

![2](https://lh3.googleusercontent.com/Stk_Ld4lHZrN7UrA9J3gM4TV9TvUt7FgIw3ITz3xWqkdod8TQYr3OELWFJ0usAUqZy5Qf17_e-NyMRjwuJXoTnkV88BzQE5PUoJKtk-zCQC6KH4vCRxbMbpMbfadfhUwwbwT33WZ)**​**

**당신의 최대 수입은 우측 파란색 입니다.**

**보시는 것 처럼 옵션의 수명\(위 이미지에서의 1시간\) 및 당신이 사용하기 원하는 가격 페어\(위의 예에서는 ETH/USD\)등과 같이 당신이 구성할 수 있는 다른 옵션이 있습니다.**

**이러한 기본\(디폴트\) 설정은 시작하기 쉬워서 심도있게 들어가서 나중에 최고의 조합을 찾을 수 있습니다.**

## **단계 4: 방향 설정**

**당신 옵션의 방향을 선택하기 위해 파란색 “UP” 또는 빨간색 “DOWN” 버튼을 누르십시오. 만일 up을 택하고 시간내에 가격이 오르면, 당신이 이깁니다. 만약 가격이 내리면, 당신은 잃게됩니다.**

![](https://lh5.googleusercontent.com/ikZytBayxTPErfwbXFetdxyWw0q3prjkUknOun-JbblWhQ5ArouTewf6cOxlzMtmQsz5v86aS3SnB8eczxmFLBx6-OS2BgHIpmwmdHY24aP1meLovRHrZy6FqMkcvvnVkTzy-Muc)

**3**

**빨강? 파랑? 당신의 선택입니다.**

## **단계 5:거래 컨펌\(확인\)**

**지갑에서 거래를 확인하세요\(여기서는 Metamask\). 만일 당신의 지갑에 에러가 있을 경우 그 거래를 보내지 마십시오.**

![](https://lh6.googleusercontent.com/R0TgNQ1-YdENom_m1BRXdHOFtNM398epFEZ3L-hkrbv8wUrGKwyt8STGmR4feL1yfoTfm7TJGVMJ3YgstS9BsTELqKvm3K09aLTI7xN_yWV3hHa5Jr4ojbEZYmZmksCCU9YArJ1U)

**4**

**거래 규모는 가스\(gas\) 수수료 보다 많게 하기를 권합니다.** 

**거래 확인을 하게 되면, 두가지의 선택이 있습니다.**

1. **잠시 쉬면서 구매를 위한 다음 하락을 지켜보는 선택을 할 수 있으며**
2. **옵션을 마무리하기 위해 행사/만료 페이지로 가는 선택을 할 수 있습니다.**

**만약 당신이 당신의 옵션을 다음 한 시간 동안 지켜볼 필요가 없다면 괜찮습니다. 누구든지 당신을 위해 그것을 완성할 수 있고 그들은 약간의 수수료\(당신 이익의 0.02%\)를 받을 것입니다. 옵션 정산에 대한 자세한 내용은 여기\(here\)를 참조하십시오.**

##  ****

## **단계별 판매 옵션** 

**발행을 위한 설명.**

## **단계 1:지갑 연결**

**BIOPset 사이트 방문 후 “연결\(Connect\)” 버튼을 누르고 당신의 지갑에 연결 하십시오.**

![](https://lh5.googleusercontent.com/YjDX3W-6cKz9gG-2wuSU2Qpb6aCbsY_WUuyG3BiCX6w22jSomsI6Zz6_6W8mnIuV3hp3rQxJVEnzsHM_H5a5kzHroj_PUHKp3dFPB1XX8YaoQSpNKfahaDJNf6iKI4jtjA6a9GU8)

**1**

**당신의 제공자를 선택하세요.**

## **단계 2:수익\(Earn\) 대화창 열기**

**지갑에 연결된 후, 메뉴 상단에 있는 “Earn”을 클릭하면 유동성 공급을 위한 발행 페이지가 열립니다.**

![](https://lh6.googleusercontent.com/zjBYf_pLCJIJ2MgPRCdFrvqNW5sL2exuH9pdybxZMIlOpfr3t_gPFtUfhol0oCX6eZ4aJf4BpRYotmFEsavRwYxlzNE5MA1eerGkzRdE1nYOVKLwhlXs8_Ut77LHaEX4vYZcC5Rr)

## **단계 3: 유동성 분담금 액수 입력**

**당신이 풀에 제공하고 싶은 액수의 ETH\(혹은 지분\)를 입력하십시오.**

![](https://lh3.googleusercontent.com/OGYdQnOp3a-cGJnvjryd3Ie3WdqkFNSkU2-xkEYF7m2bLKAk0D8WVFQFDD2wT3Y8dnGNj3BwhM9AAWv_DHdO-TblqAP7WIM-tZ2CjjRPhkTCoPf5MDqZInDXvZUIkGRCJcqrAVI4)

**당신이 스테이킹하고싶은 액수를 입력**

## **단계 4:원하는 기금 스테이킹**

**“Stake”를 클릭**

**버튼을 누르고 스테이킹 컨펌을 위해 지갑 안의 거래를 보냅니다.**

**기금을 스테이킹\(적립\)하면 현재 동결\(잠금\)기간을 알려주는 메시지를 받게 됩니다. 하지만 걱정하지 마세요, 기간이 완료되기 전에 당신의 기금에 액세스 할 필요가 있다면,  또 다른 동결 기간을 벗어나기 위해 적은 수수료\(기본 1%로 풀에 있는 모두에게 비례적 배분됨\)를 지불할 수 있습니다. 조기 출금 수수료에 대한 보다 자세한 정보는 여기\(here\)를 보십시오.**

## **단계별정산옵션**

**구매자 개입에 대한 설명**

**기간만료 후, 트레이더의 바이너리 옵션은 가치가 살아 있거나\(내가격 또는 ITM\) 무가치\(외가격 또는 OTM\)하거나 둘 중 하나입니다. 정산이란 옵션이 ITM일 경우 트레이더에게, 옵션이 OTM일 경우 발행\(유동성 풀\)에게 자금을 전해주는 과정입니다. 이것이 옵션 들을 단계별로 정하는 방법입니다.**

## **단계 1 : 가치있는 옵션의 행사**

**당신 자신에대한 0.2%의 결제 수수료를 청구하기 원합니까? “Settle\(정산\)” 페이지로 가서 당신 자신에 대한 옵션의 전체 값을 청구하십시오.**

**이동안 당신은 다른 ITM 또는 OTM 옵션을 정산함으로 다른 이들을 도울 수 있습니다.\(그리고 당신 자신에대한 리스크 없는 수수료를 벌 수 있습니다.\)**

![](https://lh5.googleusercontent.com/t9HI1ioA2vrzZ_NMgiymvYtQQ3Fp7g9En5pahXH5RAGWlLJLA4ZzzXOjgvBHAH6y75588xzmO-UPUqretRRvcHcEdbWI6bIiqQUdi6tUTAyeKDeasEOXU8cSGqR9ZDJg_wVXb72n)

**5**

**비록 당신의 옵션 선택이 틀렸더라도 그것을 기한 종료 시킴으로써 당신의 돈을 돌려 받을 수 있습니다.**

##  ****

## **FAQs**   

**다음은 BIOPset에 대해서 가장 자주 묻는 질문들 입니다.**

**여기에 본 섹션의 항목들 입니다.**

[**일반 질문**](https://docs.biopset.com/practice/faqs/most-frequent-questions)[                                         ****](https://docs.biopset.com/practice/faqs/most-frequent-questions)

[**일반적으로 가장 자주 묻는 질문들의 목록입니다.**](https://docs.biopset.com/practice/faqs/most-frequent-questions)

[**거래에관한 질문**](https://docs.biopset.com/practice/faqs/trading-questions)

[**옵션 구매자들이 가장 자주 묻는 질문들.** ](https://docs.biopset.com/practice/faqs/trading-questions)

[**발행자가 질문**](https://docs.biopset.com/practice/faqs/liquidity-provision-questions)

[**옵션 판매자들이 가장 자주 묻는 질문들**](https://docs.biopset.com/practice/faqs/liquidity-provision-questions)

##  ****

## **일반 질문**

\*\*\*\*[**일반적으로 가장 자주 묻는 질문들의 목록입니다.**](https://docs.biopset.com/practice/faqs/most-frequent-questions)

 **BIOPset에 관한 가장 일반적인 질문에 대해서는 Medium에서 긴 형식으로 답변이 되어 있습니다. 그 응답 들은 이곳에 요약되어 있습니다.**                                                                                                  

### **BIOPset은 무엇이 그렇게 특별한가요?**

 **BIOPset은 암호화화폐 가격 투기자들에게 최초의 분산화\(또는 탈중앙화\)된 바이너리 옵션 플랫폼에 온-체인\(블록체인 위\)에 액세스하게 해줍니다.**

                ****

### **중앙화 플랫폼 경쟁자들은 누구입니까?**

**언급할 수 없을 정도로 많으며, 여기에 20개의 중앙화 바이너리 옵션 플랫폼들의 리스트가 있습니다.**

### **중앙화 플랫폼 경쟁자들보다 BIOPset의 잇점은 무엇입니까?**

1.  **BIOPset에서는 최소한도가 없습니다.**
2.  **상한선은 풀의 잔고로 제한합니다.**
3.  **KYC를 이행할 의무가 없습니다.**
4. **BIOPset의 수익률은 내세울 만 합니다\(위 리스트의 20개 서비스의 83~95%와 비교해서 발행\(매도\)할 때 89.8%\).**
5. **BIOPset은 바이너리 옵션 거래를 위한 보다 원활한 플랫폼입니다. 즉, 중앙화된 서비스와 비교해서 수익 회수를 위한 대기 기간이 거의 없습니다.**

### **왜 BIOPset이 중앙화 플랫폼경쟁자들보다 안전합니까?**

**BIOPset은 거래자들에게 계좌의 신청이나 설정을 요청하지 않는 무신뢰환경\(거래의 신뢰가 필요치 않음\)의 바이너리 옵션 플랫폼입니다. 공개 발행된 스마트 계약이 모든 거래를 관리하며 BIOPset 상에서 발생되는 모든 거래들은 이더리움 블록체인을 통해서 감사\(audit\)할 수 있습니다.** 

**BIOPset 이전에는 조기 투자자/소유주들 만이 중앙화된 바이너리 거래에서 하우스 역할을 할 수 있었습니다. 이제 BIOPset은 유동성 공급자들이 하우스를 뒤에서 지원하고, BIOP 토큰 소유자들을 통해서 거래 규칙을 만들 수 있게 해 줍니다.**

### **BIOP 토큰은 무엇인가요?**

**활용 보상 제도의 일부로써 트레이더\(또는 옵션보유자/구매자\), 발행자\(또는 유동성 공급자\), 그리고 정산자들은 BIOP 거버넌스 토큰을 얻게 됩니다. 그러한 토큰은 플랫폼 관리를 위한 제안에 투표하기 위한 것입니다. 거버넌스\(의사결정\) 계획에 따라서 BIOP 토큰은 플랫폼에서 발생하는 소정의 수수료를 받을 수도 있습니다.** 

**디폴트\(기본값\)에의해 BIOP 토큰은 수수료가 없습니다. BIOP토큰에 대해 더 알고 싶다면 읽어보세요.**

### **BIOPset 활용시 어떤 위험이 있을까요?**

**BIOPset은 현재 베타버전 단계입니다. 프로그램은 꾸준하게 개선되고 있으며, 변수들은 바뀔 수도 있습니다. 결국, BIOPset은 아직까지 감사가 완료되지 않은 스마트 계약서에서 돌아가고 있습니다.** 

**간단히 말하자면, 현재 단계에서는 많은 위험이 있으며 플랫폼 사용자들은 그들의 자금을 잃게 될 수 있다는 사실을 반드시 알아야만 합니다.**

## **거래관련 질문**

\*\*\*\*[**옵션 구매자들이 가장 자주 묻는 질문들.** ](https://docs.biopset.com/practice/faqs/trading-questions)

**거래관련 FAQ는 대부분의 옵션 거래자들이 BIOPset에서 직면하는 질문에 대한 답변에 중점을 주고 있습니다. BIOPset에서 트레이더들은 항상 바이너리 옵션의 구매자/보유자이며, 풀\(또는 하우스\)가 상대편입니다.**  


## **발행자 질문**

**옵션 판매자들이 가장 자주 묻는 질문들.**

**발행자 관련 FAQ는 대부분의 유동성 공급자들이 BIOPset에서 직면하는 질문에 대한 답변에 중점을 두고 있습니다. BIOPset에서 유동성 공급자들은 항상 바이너리 옵션의 판매자/발행자들입니다.  이들은 풀\(또는 하우스\)이며 항상 소극적입니다.** 

**옵션 구매자가 상대편이며, 이들은 BIOPset 플랫폼에서 활성화된\(활발한\) 트레이더들입니다.**

## **토큰**

**본 섹션의 항목들입니다.**

[**계층형 IBCO**](https://docs.biopset.com/references/tokens/tiered-ibco)

[**본딩 곡선을 통한 BIOP토큰의 초기 오퍼링의 상세 사항들.**](https://docs.biopset.com/references/tokens/tiered-ibco)

[**리저브 본딩 곡선**](https://docs.biopset.com/references/tokens/boding-curve)

[**차후 단계의 본딩 곡선\(LSBC\)에 관한 세부사항들.**](https://docs.biopset.com/references/tokens/boding-curve)

[**보상**](https://docs.biopset.com/references/tokens/rewards)

[**BIOPset에서의 거래 채굴**](https://docs.biopset.com/references/tokens/rewards)  


## **계층형 IBCO**

[**본딩 곡선을 통한 BIOP토큰의 초기 오퍼링의 상세 사항들.**](https://docs.biopset.com/references/tokens/tiered-ibco)

**계층형 초기 본딩 곡선 오퍼링\(줄여서 ‘TIBCO’\)은 BIOP 토큰의 초기 분배 방식입니다. 주요 목적은 초기 사업전개를 위한 비용 지불과 프로토콜 유동성에 부트스트랩을 제공하기 위한 자금을 형성하는 것입니다.**

### **가격 계층\(Pricing Tiers\)**

**TIBCO는 코인들이 거래될 수 있는 6개의 각기 다른 가격층으로 구성 되어 있습니다.** 

| **Tier** | **가용 BIOP** | **ETH 가격** |
| :--- | :--- | :--- |
| **1** |    **450'000** | **0.000035** |
| **2** |    **550'000** | **0.00004** |
| **3** |    **750'000** | **0.000045** |
| **4** | **1'050'000** | **0.00005** |
| **5** | **1'400'000** | **0.000055** |
| **6** | **1'800'000** | **0.00006** |

**각 단계는 판매된 토큰의 양이 그 단계를 초과하거나 IBCO\(초기오퍼링\) 이벤트가 종료될 때까지 지속됩니다. 각 단계의 가격은 전 단계 보다 높으며, 그 이벤트는 계약이 활성화 된 시점으로부터 총 3일\(72시간\) 동안 지속 됩니다.**

### **형성된 자금의 사용처**

**첫번째 형성된 50 ETH\(이더리움\)**

**은 다음과 같이 사용하기 위해 금고로 귀속됩니다.** 

* **스마트계약 전개**
* **감사\(Audit\)**
* **호스팅서비스\(Hosting\)**
* **광고**

**나머지 이더리움은 다음과 같이 쓰여 집니다.**

* **50%\(최대 75 ETH까지\)는 유니스왑 유동성 풀에 더해 집니다.**
* **나머지는 BIOPset의 옵션 유동성 풀과 bETH 토큰 락업에 더해 집니다.**

## **리저브 본딩곡선**

**차후 단계의 본딩 곡선\(LSBC\)에 관한 세부 사항들** 

**BIOP/ETH 교환거래를 위한 영구적인 마켓**

**LSBC는 거버넌스 참여에 관심이 있는 BIOPset 프로토콜의 후발 사용자들에게 교환 거래를 쉽게할 수 있게 고안된 자동화 마켓 메이커\(AMM\)입니다. 이 시스템은 유니스왑 보상\(DEX 보상\)이 만기 종료 이후\(프로토콜 개시 후 약 7개월\)까지는 소개되지 않을 것입니다. LSBC와 함께라면, BIOP 교환거래 페어를 제공하는 유니스왑 유동성 공급자들이 없어도 상관 없으며 LSBC는 영구적인 마켓입니다.**  


**총 BIOP 공급량의 19.4%는 LSBC가 보유하게 됩니다. 계약이 개시될 때까지 그 자금들은 동결되어 손 댈 수 없으며, 출시 7개월 후 DEX 보상이 완료되면 자금은 이전되고 LSBC는 열립니다.**

**일단 운영이 개시되면, ETH를 보내면서 본딩곡선으로부터 BIOP을 구매할 수 있으며 구매후 매번 가격은 상승합니다. LSBC에는 \(이전 BIOP 판매에서 얻어진\) ETH가 남아 있지만, 누구나 본딩곡선으로부터 BIOP과 함께 ETH를 구매할 수 있습니다.**  


**이 본딩곡선은 ‘Bancor’ 본딩곡선 기초에 근거합니다. 이는 매 ETH 당 BIOP의 가격이 매매시에는 상승하고, 환매시에는 하락함을 의미합니다. LSBC의 구매와 판매 기능에는 선택적 수수료가 있으며 두가지에 대한 이러한 수수료율은 기본 0%로 설정되어 있습니다. 정산 DAO는 두 단계 작업으로 그 수수료를 변경할 수 있습니다. 이러한 메커니즘을 통해 발생한 수수료는 DAO 스테이커들이 사용할 수 있도록 결제 DAO 금고의 일부가 됩니다.** 

**BIOPset 프로토콜의 자율적이고 검열 방지적인 특성에 중요한 LSBC는 나중에 변경 시까지 BIOP을 발견하지 못할 수도 있는 모든 사람들이 활용 보상이 완료된 후에도 모든 정산DAO 활동에 완전히 참여할 수 있도록 허용합니다. 다른 무엇보다도 LSBC의 역할은 모두에게 시장 통제 가격으로 BIOP에 접근할 수 있는 장소를 제공하는 것입니다.**    


## **보상**

### **BIOPset에서 거래 채굴**

**조기 채택을 장려하고 참가자 들에게 성공적으로 소유권을 분배하는 분산화된 거버넌스 시스템으로의  전환이 BIOPset 활용 보상 계획의 목표입니다.**

##  ****

### **활용보상 요약**

**BIOPset 플랫폼과의 모든 상호작용\(거래\)에서는 BIOP 토큰을 얻게 됩니다. BIOP 보상은 그들의 투표권을 위해서 판매 혹은 보유하거나 위임될 수 있습니다.**

\*\*BIOP 버전2에서는 활용 보상이 자동으로 주어졌지만, 버전4에서는 반드시 청구해야만 합니다.

\*\*활용 보상의 캡처\(획득\)은 BIOPset 문서에서는 거래 채굴이라고도 되어 있습니다.

**정산과 거래에 대한 보상은 거래 단위로 주어집니다.**  

**발행 보상은 베팅시간\(복리로 매 9번째날\), 사용\(\*“Collatoral Locks-담보동결기간”이 길수록 복리로 증가\) 그리고 베팅 사이즈를 근거로 주어집니다.**

**\* Collatoral Locks의 의미는 상대방의 담보자산의 동결이란 뜻이고, 인출이 불가함.**   


### **발행자 활용보상의 세부내용** 

**풀에 유동성\(기여도 혹은 발행\)을 제공한 경우 매우 높은 인센티브가 주어집니다. 발행 활용 보상은 아래의 3가지 요소를 기준으로 발행자 들이 BIOP 토큰을 받도록 짜여져 있습니다.**

* **보관 기간: 발행자 보상 요소는 매 9일 기준 복리이며 그들의 유예중인 보상을 증가시킵니다.**
* **풀\(기금\) 공유 사이즈: 발행자 보상 요소는 전체 발행자 풀의 가장 큰 부분을 차지할 경우 증가합니다.**
* **컬래터럴 락 경우: 발행자 보상 요소는 새로운 옵션 작성을 위해 풀 기금의 일부가 담보자산 동결\(Collatoral Locked를 줄여서 표현\) 될 때 마다 역시 증가합니다.** 

### **거래 활용 보상의 세부내용**

**거래 보상 청구는 각 옵션이 만들어질때 정해지며 옵션의 규모에 영향을 받는데, 옵션의 규모가 크면 클수록 보상도 더 많이 받게 됩니다.**  


### **정산 활용 보상의 세부내용**

**정산 보상 청구는 각 옵션의 정산 시에 결정되며 정산 보류 중인 옵션의 숫자에 영향을 받는데 옵션의 정산이 많을수록 보상도 많습니다.**   




## **스마트 계약**

**본 섹션의 항목들 입니다.**

[**감사**](https://docs.biopset.com/references/smart-contracts/audits)

[**스마트 계약의 감사**](https://docs.biopset.com/references/smart-contracts/audits)

[**Github 보관소**](https://docs.biopset.com/references/smart-contracts/github-repository)

[**BIOPset의 Github 보관소로 연결.**](https://docs.biopset.com/references/smart-contracts/github-repository)

[**연락처 주소**](https://docs.biopset.com/references/smart-contracts/contact-addresses)

[**실시간 연락처 주소 목록**](https://docs.biopset.com/references/smart-contracts/contact-addresses)  
****

## **감사**

**스마트 계약의 감사**

**​ ITCO 감사**  


## **Github 보관소**

**BIOPset의 Github 보관소로 연결**

**BIOPset 스마트 계약들은 Github 이곳에서 호스팅 됩니다.**  


## **연락처 주소**

**실시간 연락처 주소 목록**

**다음은 이더리움 메인넷 버전4에 배치된 스마트 계약의 목록 입니다:**

1. **BIOP Token -**[ **0x29641e1096d4240b09a933839feac57b200652a4**](https://etherscan.io/address/0x29641e1096d4240b09a933839feac57b200652a4)  ****
2. **Tiered IBCO -**[ **0xe800d2d24578ee7faf01cb609c853a4a93079350**](https://etherscan.io/address/0xe800d2d24578ee7faf01cb609c853a4a93079350)**​**

\*\*\*\*

  
****  


